# Generated by Django 2.1.7 on 2019-03-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_orders', '0004_auto_20190326_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
