# Generated by Django 2.1.7 on 2019-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_orders', '0007_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deadline',
        ),
        migrations.AddField(
            model_name='order',
            name='urgency',
            field=models.IntegerField(choices=[(1, 0), (2, 1), (3, 2), (4, 3), (5, 4), (6, 5), (7, 6), (8, 7), (9, 8)], default=0),
        ),
    ]
