# Generated by Django 2.1.7 on 2019-05-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_orders', '0009_auto_20190501_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pages',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
    ]
