# Generated by Django 2.1.7 on 2019-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_orders', '0010_auto_20190501_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pdf',
            field=models.FileField(null=True, upload_to='uploads/pdfs'),
        ),
    ]
