# Generated by Django 2.1.7 on 2019-05-02 17:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_orders', '0013_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='instructions',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
