# Generated by Django 2.1.7 on 2019-05-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_orders', '0015_order_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process',
            field=models.CharField(choices=[('C', 'Processing'), ('Q', 'Finished')], default='C', max_length=10),
        ),
    ]
