# Generated by Django 2.1.7 on 2019-05-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_orders', '0017_auto_20190502_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Finished', 'Finished')], default='Processing', max_length=10),
        ),
    ]
