# Generated by Django 2.1.7 on 2019-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_orders', '0024_auto_20190502_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process',
            field=models.CharField(choices=[(1, 'Processing'), (2, 'Finished')], default='Processing', max_length=12),
        ),
    ]
